### ISSUE TITLE
Struggling to run rulstm feature extraction

### ISSUE THREAD

**Issue by Gregz9** [stevenlsw/hoi-forecast#17]
Hi,

As part of my master thesis, I was hoping to run your model on some custom data. However, I am not able to get the environment for rulstm FasterRCNN setup correctly, and the model fails with CUDNN_STATUS_NOT_INITIALIZED. Do you possibly have any docker image available in which the feature extraction stage could be run?

**Comment by stevenlsw** [comment]
Hi, 

Thanks for your interest. For feature extraction, basically you could follow [Feature Extraction in RULSTM](https://github.com/fpv-iplab/rulstm?tab=readme-ov-file#feature-extraction), for hand bbox detection you could use [hand_object_detector](https://github.com/ddshan/hand_object_detector) to get hand and object bboxes, then you could use ROI to crop the hand and object features accordingly. For `CUDNN_STATUS_NOT_INITIALIZED`, i guess it is because you have not setup the cuda successfully. Can you check your current pytorch could use cuda like `tensor.cuda()`

**Comment by Gregz9** [comment]
I managed to fix the CUDNN issue! Thank you for pointing me to hand_object_detector!
